[doc]
name = 'vita'
bundle = 'https://data1.fullyjustified.net/tlextras-2022.0r0.tar'

[[output]]
name = 'zamboni-vita'
type = 'pdf'
index = 'zamboni-vita.tex'
preamble = ''
postamble = ''

# [[output]]
# name = 'zamboni-vita.html'
# type = 'html'
# index = 'zamboni-vita.tex'
# preamble = ''
# postamble = ''

# [[output]]
# name = 'zamboni-vita-private'
# type = 'pdf'
# index = 'zamboni-vita-private.tex'
# preamble = ''
# postamble = ''

# [[output]]
# name = 'zamboni-resume'
# type = 'pdf'
# index = 'zamboni-resume.tex'
# preamble = ''
# postamble = ''
